// <auto-generated />
namespace eCommerce.Data.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class orderguestbool : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(orderguestbool));
        
        string IMigrationMetadata.Id
        {
            get { return "202004300117194_order-guest-bool"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
